// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdX4klNsSLpXlVtn-ASWMX9YlB9hJUaAk',
    appId: '1:891386873449:web:e556c211196c49165944f8',
    messagingSenderId: '891386873449',
    projectId: 'flutterjumeoni',
    authDomain: 'flutterjumeoni.firebaseapp.com',
    databaseURL: 'https://flutterjumeoni-default-rtdb.firebaseio.com',
    storageBucket: 'flutterjumeoni.appspot.com',
    measurementId: 'G-LJ1TW74NWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEe-HzKxyhXYwwX3IEOE-5U-eQqqP9ZVA',
    appId: '1:891386873449:android:14579cbd176277c15944f8',
    messagingSenderId: '891386873449',
    projectId: 'flutterjumeoni',
    databaseURL: 'https://flutterjumeoni-default-rtdb.firebaseio.com',
    storageBucket: 'flutterjumeoni.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2YoWQi3kXinCRLy39TEL5qwWtbqCM-Ww',
    appId: '1:891386873449:ios:3f72e0bec629642f5944f8',
    messagingSenderId: '891386873449',
    projectId: 'flutterjumeoni',
    databaseURL: 'https://flutterjumeoni-default-rtdb.firebaseio.com',
    storageBucket: 'flutterjumeoni.appspot.com',
    iosBundleId: 'com.example.flutterJumeoni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2YoWQi3kXinCRLy39TEL5qwWtbqCM-Ww',
    appId: '1:891386873449:ios:319dd867132584635944f8',
    messagingSenderId: '891386873449',
    projectId: 'flutterjumeoni',
    databaseURL: 'https://flutterjumeoni-default-rtdb.firebaseio.com',
    storageBucket: 'flutterjumeoni.appspot.com',
    iosBundleId: 'com.example.flutterJumeoni.RunnerTests',
  );
}
